// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddOptionDialog: typeof import('./src/components/StandsList/addOptionDialog.vue')['default']
    DetailStandard: typeof import('./src/components/detailStandard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    OptionDialog: typeof import('./src/components/StandsList/optionDialog.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/StandsList/search.vue')['default']
    StandardAside: typeof import('./src/components/StandsList/standardAside.vue')['default']
    StandardHeader: typeof import('./src/components/StandsList/standardHeader.vue')['default']
    StandardList: typeof import('./src/components/StandsList/standardList.vue')['default']
    StandsList: typeof import('./src/components/StandsList.vue')['default']
    TopConnection: typeof import('./src/components/Header/topConnection.vue')['default']
  }
}
